language: cpp

before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq libcurl4-openssl-dev libjsoncpp-dev libargtable2-dev libboost-test-dev libgnutls-dev libgcrypt11-dev valgrind wget
 - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
 - wget ftp://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.38.tar.gz
 - tar -xvf libmicrohttpd-0.9.38.tar.gz
 - cd libmicrohttpd-0.9.38
 - ./configure && make
 - sudo make install && sudo ldconfig
 - cd .. && sudo rm -rf libmicrohttpd-0.9.38
 - sudo pip install cpp-coveralls

env:
 - HTTP_SERVER=YES HTTP_CLIENT=YES COMPILE_STUBGEN=YES

compiler:
  - gcc

script: 
    - mkdir -p build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DHTTP_CLIENT=${HTTP_CLIENT} -DHTTP_SERVER=${HTTP_SERVER} -DCOMPILE_STUBGEN=${COMPILE_STUBGEN} .. 
    - make
    - valgrind --leak-check=full --error-exitcode=1 ./bin/unit_testsuite
    - make test
    - sudo make install && sudo ldconfig
    - g++-4.8 ../src/examples/simpleclient.cpp -ljsonrpccpp-client -ljsoncpp -ljsonrpccpp-common -lcurl -o sampleclient
    - g++-4.8 ../src/examples/simpleserver.cpp -ljsonrpccpp-server -ljsoncpp -ljsonrpccpp-common -lmicrohttpd -o sampleserver
    - sudo make uninstall
after_success:
    - cd ..
    - coveralls --gcov /usr/bin/gcov-4.8 -e src/test -e src/examples -e cmake -e /usr/include -e build/CMakeFiles -E '.*\.h' -E 'libmicrohttpd.*'
